plugins:

  requests:
    executor: central_deployment_agent
    source: https://github.com/cloudify-examples/cloudify-requests-plugin/archive/master.zip
    package_name: cloudify-requests-plugin
    package_version: '0.0.1.dev3'

data_types:

  cloudify.datatypes.URI:
    properties:
      protocol:
        description: >
          The IP Protocol.
        type: string
        default: 'http'
        required: true # This is redundant because a default is provided. We discourage redundancy, but do so here for instruction.
      domain:
        description: >
          The URI domain.
        type: string
        required: true
      path:
        description: >
          Additional URI path.

  cloudify.datatypes.file:
    properties:
      filename:
        description: >
          The filename as you want to send it in the request.
        type: string
        required: true
      path:
        description: >
          The path relative to the blueprint.yaml the file is packaged with the blueprint. Note: this and url are mutually exclusive.
          The plugin will check this first.
        type: string
        required: false
      url:
        description: >
          If the file should be downloaded from a URL. Note: this and path are mutually exclusive.
        type: cloudify.datatypes.URI
        required: false

  cloudify.datatypes.auth:
    properties:
      username:
        required: true
      password:
        required: true

node_types:

  cloudify.nodes.requests.Object:
    derived_from: cloudify.nodes.Root
    properties:
      endpoint:
        description: The API object endpoint.
        type: cloudify.datatypes.URI
        required: true
      configuration:
        description: >
          The configuration of the API Resource that you are managing.
          No validation is provided for the cloudify.nodes.requests.Object type.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: requests.cloudify_requests.request
          inputs:
            method:
              default: POST
            headers:
              default: {} # not tested
            files:
              description: A list of cloudify.datatypes.requests.file.
              default: []
            data:
              default: { get_property: [ SELF, configuration ] }
            json:
              default: {} # not tested
            params:
              default: {} # not tested
            auth:
              description: A username and password in cloudify.datatypes.auth.
              default: {}
            cookies:
              default: {} # not tested
            hooks:
              default: {} # not tested
        delete:
          implementation: requests.cloudify_requests.request
          inputs:
            method:
              default: DELETE
            headers:
              default: {} # not tested
            files:
              description: A list of cloudify.datatypes.file.
              default: []
            data:
              default: {}
            json:
              default: {} # not tested
            params:
              default: {} # not tested
            auth:
              description: A username and password in cloudify.datatypes.auth.
              default: {}
            cookies:
              default: {} # not tested
            hooks:
              default: {} # not tested
