plugins:

  req:
    executor: central_deployment_agent
    source: https://github.com/cloudify-examples/cloudify-requests-plugin/archive/master.zip
    package_name: cloudify-requests-plugin
    package_version: '0.0.1.dev0'
